---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cdn 
spec:
  tls:
    - hosts:
      - cdn.onni.live 
      secretName: tls-secret
  rules:
    - host: cdn.onni.live 
      http:
        paths:
        - path: /
          backend:
            serviceName: cdn-svc
            servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
  labels:
    app: cdn-svc
spec:
  ports:
  - port: 80
    targetPort: 80 
    protocol: TCP
    name: http
  selector:
    app: cdn
